name: GitHub Pull Request Auto Assign
description: "Assign author to pull requests when the pull requests are opened."
author: "samaronybarros"

inputs:
  repo-token:
    description: "The repository token"
    default: ${{ github.token }}

runs:
  using: "node16"
  main: "dist/index.js"
