name: "Auto Author Assign"

on:
  pull_request_target:
    types: [opened, reopened]

permissions:
  pull-requests: write

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Use Node.js v${{ matrix.node-version }}"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: "Install and build"
        run: npm install && npm run build

      - name: "Assign author"
        run: npm start
